product/urls.py
from django.urls import path

from product.views import ProductListView, ProductDetailView

app_name = 'product'

urlpatterns = [
    path('all-products/', ProductListView.as_view(), name='product_list'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail')
]

swandoo_website/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from product.views import ProductListView
from django.views.generic import TemplateView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('product/', include('product.urls', namespace='product')),
                  path('', ProductListView.as_view(), name='main'),
                  path('about-us/', TemplateView.as_view(template_name='about.html'), name='about_view'),
                  path('__debug__/', include('debug_toolbar.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href={% static 'style/css/about.css' %}></link>
<link rel="stylesheet" href="{% static 'style/css/swiper.min.css' %}">

{% endblock style %}


{% block content %}
<section class="section-offset">
    <div class="row">
    <div class="container">
        <h1 class="text-center about-us-h1">Добро пожаловать в семью <span class='latin'>Swandoo</span></h1>
        <h2 class="text-center about-us-h2">
            Мы молодая команда, которая помогает семьям найти простые жизненные решения для радостной
             и сбалансированной жизни.
        </h2>
        <div class="col-12">
            <img class="about-us__image" src="{% static 'img/swandoo_team.jpg' %}" alt="Семья Swandoo">
        </div>
        </div>
    </div>
    <div class="row">
        <div class="container">
            <div class="col-12 mt-2">
                <h4 class="about-us__h4">КТО ТАКИЕ <span class="latin"><b>SWANDOO</b></span>?</h4>
                <article class="about-us__descr">
                    <p>
                        <span class="latin">Swandoo</span> как бренд основан в&nbsp;Австрии, в&nbsp;Вене, командой неординарно мыслящих дизайнеров и&nbsp;инженеров.Мы дотошны к&nbsp;своем отношении к&nbsp;безопасности и&nbsp;качеству продукта. Большинство из&nbsp;нас родители и&nbsp;мы&nbsp;используем наши автокресла с&nbsp;нашими детьми.
                    </p>
                    <br>
                    <p>
                        Как любой родитель, мы&nbsp;хотим максимальной безопасности для наших непосед. К&nbsp;сожалению, продукты, которые мы&nbsp;находили на&nbsp;рынке, не&nbsp;отвечали нашим требованиям к&nbsp;качеству и&nbsp;безопасности. Многие напоминали реквизит из&nbsp;дешевых научно-фантастических фильмов, а&nbsp;некоторые даже из&nbsp;фильмов ужасов!
                    </p>
                    <br>
                    <p>
                        Мы&nbsp;решили взять дело в&nbsp;свои руки, полагаясь на&nbsp;наш опыт в&nbsp;развитии инновационных продуктов. Мы&nbsp;взяли на&nbsp;себя ответственность и&nbsp;расширили стандарты производства детских автокресел. И&nbsp;мы&nbsp;не&nbsp;могли больше остановиться! Мы&nbsp;стремимся создавать лучшие продукты из&nbsp;возможных на&nbsp;сегодняшний день. Мы&nbsp;всегда будем улучшать наши автокресла. Потому, что для нас это очень-очень важно.
                    </p>
                </article>
                <!---TODO-->
                <a href="" class="image-slider__btn">Продукция</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="container">
            <div class="swiper mySwiper">
                <div class="swiper-wrapper">
                    <div class="swiper-slide">
                        <img class="about-us__swiper-img" src="{% static 'img/about_us_img/slide-1.png' %}" alt="">
                    </div>
                    <div class="swiper-slide">
                        <img class="about-us__swiper-img" src="{% static 'img/about_us_img/slide-2.png' %}" alt="">
                    </div>
                    <div class="swiper-slide">
                        <img class="about-us__swiper-img" src="{% static 'img/about_us_img/slide-3.png' %}" alt="">
                    </div>
                    <div class="swiper-slide">
                        <img class="about-us__swiper-img" src="{% static 'img/about_us_img/slide-4.png' %}" alt="">
                    </div>
                    <div class="swiper-slide">
                        <img class="about-us__swiper-img" src="{% static 'img/about_us_img/slide-5.png' %}" alt="">
                    </div>
                    <div class="swiper-slide">
                        <img class="about-us__swiper-img" src="{% static 'img/about_us_img/slide-6.png' %}" alt="">
                    </div>
                </div>
                <div class="swiper-pagination"></div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
            </div>
        </div>
    </div>
    
</section>
{% endblock content %}
{% block style_js %}
<script src="{% static 'style/js/swiper.min.js' %}"></script>
<script src="{% static 'style/js/about.js' %}"></script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Swandoo официальный сайт{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style/css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'style/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'style/css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'style/css/burger.css' %}">
  {% block style %} {% endblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
<section>
  <div class="container-fluid">
    <nav class="header_nav {% if request.path != '/' %} white-bg {% endif %}">
      <div class="logo">
        <a href="{% url 'main' %}">
          <img class="" src="
              {% if request.path != "/" %}{% static 'img/logo_blue.svg' %}{% else %}{% static 'img/logo_white.svg' %}{% endif %}"
               alt="Swandoo - всегда с Вами">
        </a>
      </div>
      <div id="burgerMenu" class="burger {% if request.path != '/' %}burger-blue{% endif %}">
        <span class="burger__burger-line"></span>
        <span class="burger__burger-line"></span>
        <span class="burger__burger-line"></span>
      </div>
      <div id="menuBurgerItems" class="header-nav__items">
        <ul class="header-nav__list">
          <li class="header-nav__item">
            <ul>
              <li class="latin  header-nav__item__section">
                <a href="{% url 'about_view' %}" class="header-nav__item__link">SWANDOO</a>
                <ul>
                  <li class="item__sub__menu">
                    <a href="{% url 'about_view' %}">О бренде</a>
                  </li>
                  <li class="item__sub__menu">
                    <!-- TODO -->
                    <a href="#">Где нас найти</a>
                  </li>
                  <li class="item__sub__menu">
                    <!-- TODO -->
                    <a href="#">Сотрудничество</a>
                  </li>
                </ul>
              </li>
               <li class="header-nav__item__section">
                <a href="" class="header-nav__item__link">Наши товары</a>
                <ul>
                  {% for model in models_footer %}
                    <li class="latin item__sub__menu">
                      <a href="{% url 'product:product_detail' model.slug %}">{{ model.name }}</a>
                    </li>
                  {% endfor %}
                </ul>
            </ul>
          </li>
          <li class="header-nav__item">Секция 2</li>
          <li class="header-nav__item">Секция 3</li>
        </ul>
      </div>
    </nav>
  </div>
</section>
{% block content %}{% endblock %}
<footer>
  <div class="light-bg">
    <div class="d-flex justify-content-center">
      <a class="elementor-icon" href="https://swandoo.com/newsletter/">
        <svg xmlns="http://www.w3.org/2000/svg" id="Layer_1" data-name="Layer 1" viewBox="0 0 40 40">
          <defs>
            <style>.cls-1, .cls-2 {
                fill: #e03c31;
            }

            .cls-1 {
                opacity: 0.3;
            }</style>
          </defs>
          <path class="cls-1"
                d="M20.11,35.85a.53.53,0,0,1-.25-.05C1.43,27.2,3.71,14.63,3.74,14.5s.7-6.38,6.41-8.92c4.77-2.12,8.72.57,10,1.58a9.58,9.58,0,0,1,10-1.58c5.6,2.49,6.36,8.49,6.41,9,.12.74,1.82,12.88-16.13,21.26A.52.52,0,0,1,20.11,35.85Z"></path>
          <path class="cls-2"
                d="M20.11,36.5a1.17,1.17,0,0,1-.52-.12C1.21,27.81,3,15.21,3.1,14.41,3.16,13.9,4,7.62,9.89,5A10.16,10.16,0,0,1,20.11,6.35,10.15,10.15,0,0,1,30.33,5c5.83,2.59,6.7,8.69,6.79,9.46s1.82,13.39-16.5,21.93A1.13,1.13,0,0,1,20.11,36.5Zm0-1.28ZM13.81,5.43a8.37,8.37,0,0,0-3.4.74c-5.43,2.41-6,8.33-6,8.39a.17.17,0,0,1,0,.07c0,.12-2.06,12.25,15.74,20.57C37.68,27,35.93,15.14,35.85,14.64v0c0-.25-.72-6.08-6-8.44a8.87,8.87,0,0,0-9.29,1.49.64.64,0,0,1-.82,0A9.61,9.61,0,0,0,13.81,5.43ZM7.42,16.17h-.1a.63.63,0,0,1-.53-.74c0-.22,1-5.48,5.25-7.07a.65.65,0,0,1,.45,1.21c-3.59,1.33-4.42,6-4.43,6.08A.64.64,0,0,1,7.42,16.17Z"></path>
        </svg>
      </a>
    </div>
    <div class="text-center">
      <p></p>
    </div>
  </div>
  <nav class="dark-bg">
    <div class="container">
      <div class="row">

        <div class="col-sm-12 col-md-6 col-lg-3 my-2">
          <h3 class="footer__item-title">
            <a href="{% url 'about_view' %}">О нас</a>
          </h3>
          <ul class="footer-list flex-column">
            <li class="footer__item">
              <a href="{% url 'about_view' %}">Познакомтесь с cемьей Swandoo</a>
            </li>
            <li class="footer__item">Сотрудничество с нами</li>
          </ul>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-3 my-2">
          <h3 class="footer__item-title">Где нас найти</h3>
          <ul class="footer-list flex-column">
            <li class="footer__item">Мы на OZON</li>
            <li class="footer__item">Наши партнеры</li>
          </ul>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-3 my-2">
          <h3 class="footer__item-title">Наша продукция</h3>
          <ul class="footer-list flex-column">
            {% for model in models_footer %}
              <li class="footer__item">
                <a href="{% url 'product:product_detail' model.slug %}">{{ model.name }}</a>
              </li>
            {% endfor %}
          </ul>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-3 my-2">
          <h3 class="footer__item-title">Поддержка</h3>
          <ul class="footer-list flex-column">
            <li class="footer__item">По вопросам гарантии</li>
          </ul>
        </div>
        <div class="col-12">
          <a href="{% url 'main' %}">
            <img class='footer__tree' src="https://www.swandoo.com/wp-content/themes/Swandoo_theme/img/tree.svg" alt="">
          </a>
        </div>
      </div>

    </div>

  </nav>
</footer>
<script rel="stylesheet" type="application/javascript"
        src="{% static 'style/js/bootstrap.min.js' %}"></script>
<script rel="stylesheet" type="application/javascript" type="text/javascript"
        src="{% static 'style/js/burger.js' %}"></script>
<script rel="stylesheet" type="application/javascript" type="text/javascript"
        src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script rel="stylesheet" type="application/javascript" type="text/javascript"
        src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% block style_js %}{% endblock %}
</body>
</html>